"""gdlf mitmproxy addon.

For every request:
  1. Ask rules-svc what to do (decision API).
  2. If 'block': short-circuit with a synthetic 403 + block page.
  3. Either way, POST the event to rules-svc so it shows up in Activity.

The client IP is the kid's WG peer address — mitmproxy's transparent mode
preserves the original source IP, so this maps cleanly to a kid via kids.yaml.

For TLS connections we can't decrypt (the device hasn't installed the CA),
mitmproxy signals this as a `tls_failed` hook; we then log an SNI-only event
so the parent can at least see what hosts were reached.
"""
from __future__ import annotations

import asyncio
import base64
import fnmatch
import logging
import os
from pathlib import Path

import httpx
from mitmproxy import ctx, http
from mitmproxy.tls import TlsData


def _gandalf_data_url() -> str:
    p = Path(__file__).resolve().parent / "gandalf.png"
    if not p.exists():
        return ""
    return "data:image/png;base64," + base64.b64encode(p.read_bytes()).decode("ascii")


GANDALF = _gandalf_data_url()

RULES_SVC_URL = os.environ.get("RULES_SVC_URL", "http://rules-svc:8080")
TIMEOUT = httpx.Timeout(2.0, connect=1.0)

# Hosts we silently drop from sni_only logs — pinned background traffic
# generated by the OS / Google Mobile Services that we can't decrypt and
# don't care about. Glob patterns, matched case-insensitively against the
# SNI hostname. If a parent wants forensic detail, we can add a 'verbose
# mode' toggle later that bypasses this list.
SNI_NOISE_PATTERNS = (
    "*.googleapis.com",
    "*.gstatic.com",
    "*.google-analytics.com",
    "*.crashlytics.com",
    "*.googletagmanager.com",
    "*.doubleclick.net",
    "play.googleapis.com",
    "android.clients.google.com",
    "connectivitycheck.gstatic.com",
    "fonts.gstatic.com",
    "ssl.gstatic.com",
    "*.firebaseio.com",
    "*.firebase.com",
    "firebaseinstallations.googleapis.com",
    "*.icloud.com",
    "*.apple.com",
    "*.mzstatic.com",
    "courier.push.apple.com",
)


def _is_sni_noise(host: str) -> bool:
    host = (host or "").lower()
    return any(fnmatch.fnmatchcase(host, p) for p in SNI_NOISE_PATTERNS)


# Sec-Fetch-Dest values that map to "asset" (sub-resource, not a navigation).
# Modern browsers (Chrome / Firefox / Safari / Edge / Android Chrome) set
# this on every request. See:
# https://developer.mozilla.org/docs/Web/HTTP/Headers/Sec-Fetch-Dest
_SEC_FETCH_ASSET = {
    "image", "audio", "video", "track", "font",
    "script", "style", "manifest", "worker", "sharedworker", "serviceworker",
    "embed", "object",
    # Beacons / pings / fonts — definitely not page navigations.
    "report", "paintworklet", "audioworklet",
}
_SEC_FETCH_PAGE = {"document", "iframe", "frame", "nested-document"}

# Accept-header fallback for clients that don't set Sec-Fetch-Dest.
def _from_accept(accept: str) -> str | None:
    accept = (accept or "").lower()
    # text/html appears in Chrome's Accept for navigation but ALSO in fetch()
    # if the caller is lazy. Only treat as page if text/html is the FIRST
    # preference (real navigations almost always start with it).
    primary = accept.split(",", 1)[0].strip()
    if primary.startswith("text/html"):
        return "page"
    for prefix in ("image/", "audio/", "video/", "font/"):
        if prefix in accept:
            return "asset"
    if "application/javascript" in accept or "text/css" in accept:
        return "asset"
    # JSON / GraphQL / gRPC-web / protobuf — almost always XHR / fetch.
    for marker in (
        "application/json", "application/graphql", "application/grpc",
        "application/x-protobuf", "application/vnd.api+json", "+json",
    ):
        if marker in accept:
            return "xhr"
    return None


# Last-resort URL-extension fallback for ancient clients / native apps.
_ASSET_EXTS = {
    ".js", ".mjs", ".css", ".map",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".ico", ".avif",
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".mp4", ".webm", ".m4s", ".ts", ".m3u8", ".mpd",
    ".mp3", ".aac", ".ogg", ".flac", ".wav",
}


def _classify(req) -> str:
    """Return 'page' | 'iframe' | 'asset' | 'xhr' | 'ws' for the given request.

    Order of confidence:
      1. WebSocket upgrade (Connection: upgrade + Upgrade: websocket)
      2. Sec-Fetch-Dest (browser's explicit declaration)
      3. Request body content-type / accept header
      4. Method (non-GET is almost never a navigation)
      5. URL extension
    Default 'page' only when every signal is silent.
    """
    h = req.headers
    # WebSocket upgrade — very common in SPA / realtime apps (Reddit's
    # gql-realtime.reddit.com/query is exactly this).
    if "websocket" in (h.get("Upgrade") or "").lower():
        return "ws"
    dest = (h.get("Sec-Fetch-Dest") or "").lower()
    if dest == "websocket":
        return "ws"
    if dest == "document":
        return "page"
    if dest in ("iframe", "frame", "nested-document"):
        return "iframe"
    if dest in _SEC_FETCH_ASSET:
        return "asset"
    if dest == "empty":
        return "xhr"

    # The request body itself tells us a lot: JSON/protobuf/form bodies are
    # XHR/POSTs, never page loads.
    ctype = (h.get("Content-Type") or "").lower()
    if any(m in ctype for m in (
        "application/json", "application/graphql", "application/grpc",
        "application/x-protobuf", "application/x-www-form-urlencoded",
        "multipart/form-data",
    )):
        return "xhr"

    guess = _from_accept(h.get("Accept", ""))
    if guess:
        return guess

    # Non-GET methods are almost never page navigations.
    if req.method.upper() not in ("GET", "HEAD"):
        return "xhr"

    # URL extension fallback.
    path = req.path.split("?", 1)[0]
    last = path.rsplit("/", 1)[-1].lower()
    if "." in last:
        ext = "." + last.rsplit(".", 1)[-1]
        if ext in _ASSET_EXTS:
            return "asset"
    return "page"

# Static HTML — no format placeholders, no KeyError risk. The Gandalf
# image is inlined as a data: URL so the block page renders without any
# extra network requests (we're on a blocked URL — there's no other
# origin the device can reach).
BLOCK_PAGE = ("""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Blocked</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
 body{font-family:-apple-system,BlinkMacSystemFont,system-ui,sans-serif;
      background:#0f1115;color:#e6e8ee;margin:0;
      display:flex;align-items:center;justify-content:center;min-height:100vh}
 .card{max-width:720px;padding:40px;text-align:center}
 .card img{width:min(440px,80vw);height:auto;margin:0 auto 20px;display:block;
           filter:drop-shadow(0 6px 32px rgba(0,0,0,0.45))}
 h1{font-size:28px;margin:0 0 12px;color:#fff}
 p{margin:8px 0;line-height:1.5;color:#a8b0c0}
 .note{margin-top:24px;font-size:12px;color:#6b7186}
</style></head>
<body><div class="card">
  <img src="__GANDALF__" alt="">
  <h1>You shall not pass</h1>
  <p>Ask a parent if you think this is a mistake.</p>
  <div class="note">gdlf</div>
</div></body></html>""").replace("__GANDALF__", GANDALF).encode("utf-8")


class GdlfAddon:
    def __init__(self) -> None:
        self._client = httpx.AsyncClient(timeout=TIMEOUT)
        self._log = logging.getLogger("gdlf")

    async def _decision(self, client_ip: str, host: str, path: str, query: str | None) -> dict:
        try:
            r = await self._client.post(
                f"{RULES_SVC_URL}/api/decision",
                json={
                    "client_ip": client_ip,
                    "host": host,
                    "path": path,
                    "query": query or "",
                },
            )
            r.raise_for_status()
            return r.json()
        except Exception as e:
            self._log.warning("decision lookup failed: %s", e)
            # Fail open — don't lock the kid out if rules-svc is down.
            return {"action": "allow", "kid": None, "rule": None, "flag": False}

    def _post_event(self, payload: dict) -> None:
        # Fire-and-forget; never block the user's request on this.
        asyncio.create_task(self._send_event(payload))

    async def _send_event(self, payload: dict) -> None:
        try:
            await self._client.post(f"{RULES_SVC_URL}/api/events", json=payload)
        except Exception as e:
            self._log.debug("event post failed: %s", e)

    async def request(self, flow: http.HTTPFlow) -> None:
        req = flow.request
        client_ip = flow.client_conn.peername[0] if flow.client_conn.peername else ""
        host = req.pretty_host
        path = req.path.split("?", 1)[0] if "?" in req.path else req.path
        # Always pass a string-or-None — earlier we relied on `req.query.fields`
        # truthiness, but empty-fields returns an empty *list* which (after JSON
        # round-trip) violated the DB's TEXT column and crashed the event insert.
        query = req.url.split("?", 1)[1] if "?" in req.url else None

        decision = await self._decision(client_ip, host, path, query)
        action = decision.get("action", "allow")
        rule = decision.get("rule")
        kid = decision.get("kid")
        flag = bool(decision.get("flag"))

        if action == "block":
            flow.response = http.Response.make(
                403, BLOCK_PAGE, {"Content-Type": "text/html; charset=utf-8"},
            )

        self._post_event(
            {
                "client_ip": client_ip,
                "method": req.method,
                "host": host,
                "path": path,
                "query": query,
                "decision": action if action in {"allow", "block", "flag"} else "allow",
                "rule": rule,
                "flag": flag,
                "sni_only": False,
                "status": 403 if action == "block" else None,
                "kind": _classify(req),
            }
        )

    async def response(self, flow: http.HTTPFlow) -> None:
        # We log at request time; nothing extra to do here for now.
        pass

    def tls_failed_client(self, data: TlsData) -> None:
        """The client refused our cert — log the SNI we saw so the parent
        knows *which* host was reached, even if we couldn't see inside."""
        try:
            host = data.context.client.sni or ""
            client_ip = data.context.client.peername[0] if data.context.client.peername else ""
        except Exception:
            return
        if not host or _is_sni_noise(host):
            return
        self._post_event(
            {
                "client_ip": client_ip,
                "method": None,
                "host": host,
                "path": None,
                "query": None,
                "decision": "sni_only",
                "rule": None,
                "flag": False,
                "sni_only": True,
                "status": None,
                "kind": "unknown",
            }
        )


addons = [GdlfAddon()]
