"""gdlf mitmproxy addon.

For every request:
  1. Ask rules-svc what to do (decision API).
  2. If 'block': short-circuit with a synthetic 403 + block page.
  3. Either way, POST the event to rules-svc so it shows up in Activity.

The client IP is the kid's WG peer address — mitmproxy's transparent mode
preserves the original source IP, so this maps cleanly to a kid via kids.yaml.

For TLS connections we can't decrypt (the device hasn't installed the CA),
mitmproxy signals this as a `tls_failed` hook; we then log an SNI-only event
so the parent can at least see what hosts were reached.
"""
from __future__ import annotations

import asyncio
import base64
import fnmatch
import logging
import os
import time
from pathlib import Path

import httpx
from mitmproxy import ctx, http
from mitmproxy.tls import ClientHelloData, TlsData


def _gandalf_data_url() -> str:
    p = Path(__file__).resolve().parent / "gandalf.png"
    if not p.exists():
        return ""
    return "data:image/png;base64," + base64.b64encode(p.read_bytes()).decode("ascii")


GANDALF = _gandalf_data_url()

RULES_SVC_URL = os.environ.get("RULES_SVC_URL", "http://rules-svc:8080")
TIMEOUT = httpx.Timeout(2.0, connect=1.0)

# How often to refresh the per-IP passthrough host list from rules-svc.
PASSTHROUGH_REFRESH_SECS = 30
# Dedup window for repeated TLS events (failures + passthroughs). Pinned-cert
# apps retry aggressively — without this, a single broken app spams 10s of
# events per minute. Tunable via env for debugging.
TLS_EVENT_DEDUP_SECS = int(os.environ.get("TLS_EVENT_DEDUP_SECS", "60"))

# Hosts we silently drop from sni_only logs — pinned background traffic
# generated by the OS / Google Mobile Services that we can't decrypt and
# don't care about. Glob patterns, matched case-insensitively against the
# SNI hostname. If a parent wants forensic detail, we can add a 'verbose
# mode' toggle later that bypasses this list.
SNI_NOISE_PATTERNS = (
    "*.googleapis.com",
    "*.gstatic.com",
    "*.google-analytics.com",
    "*.crashlytics.com",
    "*.googletagmanager.com",
    "*.doubleclick.net",
    "play.googleapis.com",
    "android.clients.google.com",
    "connectivitycheck.gstatic.com",
    "fonts.gstatic.com",
    "ssl.gstatic.com",
    "*.firebaseio.com",
    "*.firebase.com",
    "firebaseinstallations.googleapis.com",
    "*.icloud.com",
    "*.apple.com",
    "*.mzstatic.com",
    "courier.push.apple.com",
)


def _is_sni_noise(host: str) -> bool:
    host = (host or "").lower()
    return any(fnmatch.fnmatchcase(host, p) for p in SNI_NOISE_PATTERNS)


# Bulk-CDN passthrough list is sourced from rules-svc at runtime (see
# `gdlf/bulk_cdns.py`). The addon polls /api/passthrough and reads `globals`
# from the response — same loop that already syncs the per-kid hosts.
# A tiny hardcoded fallback covers the cold-start window before the first
# successful poll, plus the case where rules-svc is briefly unavailable;
# without it, a stack restart would let Steam etc. through mitm with full
# decrypt cost for ~30s.
_BULK_CDN_FALLBACK: tuple[str, ...] = (
    "*.steamcontent.com",
    "*.windowsupdate.com",
    "*.dl.delivery.mp.microsoft.com",
)


# Sec-Fetch-Dest values that map to "asset" (sub-resource, not a navigation).
# Modern browsers (Chrome / Firefox / Safari / Edge / Android Chrome) set
# this on every request. See:
# https://developer.mozilla.org/docs/Web/HTTP/Headers/Sec-Fetch-Dest
_SEC_FETCH_ASSET = {
    "image", "audio", "video", "track", "font",
    "script", "style", "manifest", "worker", "sharedworker", "serviceworker",
    "embed", "object",
    # Beacons / pings / fonts — definitely not page navigations.
    "report", "paintworklet", "audioworklet",
}
_SEC_FETCH_PAGE = {"document", "iframe", "frame", "nested-document"}

# Accept-header fallback for clients that don't set Sec-Fetch-Dest.
def _from_accept(accept: str) -> str | None:
    accept = (accept or "").lower()
    # text/html appears in Chrome's Accept for navigation but ALSO in fetch()
    # if the caller is lazy. Only treat as page if text/html is the FIRST
    # preference (real navigations almost always start with it).
    primary = accept.split(",", 1)[0].strip()
    if primary.startswith("text/html"):
        return "page"
    for prefix in ("image/", "audio/", "video/", "font/"):
        if prefix in accept:
            return "asset"
    if "application/javascript" in accept or "text/css" in accept:
        return "asset"
    # JSON / GraphQL / gRPC-web / protobuf — almost always XHR / fetch.
    for marker in (
        "application/json", "application/graphql", "application/grpc",
        "application/x-protobuf", "application/vnd.api+json", "+json",
    ):
        if marker in accept:
            return "xhr"
    return None


# Last-resort URL-extension fallback for ancient clients / native apps.
_ASSET_EXTS = {
    ".js", ".mjs", ".css", ".map",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".ico", ".avif",
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".mp4", ".webm", ".m4s", ".ts", ".m3u8", ".mpd",
    ".mp3", ".aac", ".ogg", ".flac", ".wav",
}


def _classify(req) -> str:
    """Return 'page' | 'iframe' | 'asset' | 'xhr' | 'ws' for the given request.

    Order of confidence:
      1. WebSocket upgrade (Connection: upgrade + Upgrade: websocket)
      2. Sec-Fetch-Dest (browser's explicit declaration)
      3. Request body content-type / accept header
      4. Method (non-GET is almost never a navigation)
      5. URL extension
    Default 'page' only when every signal is silent.
    """
    h = req.headers
    # WebSocket upgrade — very common in SPA / realtime apps (Reddit's
    # gql-realtime.reddit.com/query is exactly this).
    if "websocket" in (h.get("Upgrade") or "").lower():
        return "ws"
    dest = (h.get("Sec-Fetch-Dest") or "").lower()
    if dest == "websocket":
        return "ws"
    if dest == "document":
        return "page"
    if dest in ("iframe", "frame", "nested-document"):
        return "iframe"
    if dest in _SEC_FETCH_ASSET:
        return "asset"
    if dest == "empty":
        return "xhr"

    # The request body itself tells us a lot: JSON/protobuf/form bodies are
    # XHR/POSTs, never page loads.
    ctype = (h.get("Content-Type") or "").lower()
    if any(m in ctype for m in (
        "application/json", "application/graphql", "application/grpc",
        "application/x-protobuf", "application/x-www-form-urlencoded",
        "multipart/form-data",
    )):
        return "xhr"

    guess = _from_accept(h.get("Accept", ""))
    if guess:
        return guess

    # Non-GET methods are almost never page navigations.
    if req.method.upper() not in ("GET", "HEAD"):
        return "xhr"

    # URL extension fallback.
    path = req.path.split("?", 1)[0]
    last = path.rsplit("/", 1)[-1].lower()
    if "." in last:
        ext = "." + last.rsplit(".", 1)[-1]
        if ext in _ASSET_EXTS:
            return "asset"
    return "page"

# Static HTML — no format placeholders, no KeyError risk. The Gandalf
# image is inlined as a data: URL so the block page renders without any
# extra network requests (we're on a blocked URL — there's no other
# origin the device can reach).
BLOCK_PAGE = ("""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Blocked</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
 body{font-family:-apple-system,BlinkMacSystemFont,system-ui,sans-serif;
      background:#0f1115;color:#e6e8ee;margin:0;
      display:flex;align-items:center;justify-content:center;min-height:100vh}
 .card{max-width:720px;padding:40px;text-align:center}
 .card img{width:min(440px,80vw);height:auto;margin:0 auto 20px;display:block;
           filter:drop-shadow(0 6px 32px rgba(0,0,0,0.45))}
 h1{font-size:28px;margin:0 0 12px;color:#fff}
 p{margin:8px 0;line-height:1.5;color:#a8b0c0}
 .note{margin-top:24px;font-size:12px;color:#6b7186}
</style></head>
<body><div class="card">
  <img src="__GANDALF__" alt="">
  <h1>You shall not pass</h1>
  <p>Ask a parent if you think this is a mistake.</p>
  <div class="note">gdlf</div>
</div></body></html>""").replace("__GANDALF__", GANDALF).encode("utf-8")


class GdlfAddon:
    def __init__(self) -> None:
        self._client = httpx.AsyncClient(timeout=TIMEOUT)
        self._log = logging.getLogger("gdlf")
        # ip -> [glob, ...]; refreshed by _passthrough_refresh_loop.
        self._passthrough: dict[str, list[str]] = {}
        # Bulk-CDN globs — same refresh loop, applies to all clients.
        self._bulk_cdn: tuple[str, ...] = _BULK_CDN_FALLBACK
        # Client IPs that are currently network-blocked (schedule / manual).
        # We refuse to passthrough TLS for these — falling through to MITM lets
        # /api/decision serve the block page. Without this, passthrough silently
        # bypasses schedule enforcement (nft's :443 reject exempts mitm clients
        # and trusts mitmproxy to enforce policy at the decision layer).
        self._blocked_ips: frozenset[str] = frozenset()
        self._passthrough_task: asyncio.Task | None = None
        # (client_ip, host, decision) -> monotonic timestamp of last emit;
        # used to suppress repeated TLS failure / passthrough events from
        # aggressively-retrying pinned-cert apps.
        self._tls_event_seen: dict[tuple[str, str, str], float] = {}

    def running(self) -> None:
        """mitmproxy lifecycle hook — kick off the passthrough refresh task
        on the running event loop. Can't do this in __init__ because the
        event loop isn't running yet at addon-import time."""
        if self._passthrough_task is None:
            self._passthrough_task = asyncio.create_task(self._passthrough_refresh_loop())

    async def _passthrough_refresh_loop(self) -> None:
        while True:
            try:
                r = await self._client.get(f"{RULES_SVC_URL}/api/passthrough")
                r.raise_for_status()
                body = r.json() or {}
                by_ip = body.get("by_ip") or {}
                self._passthrough = {
                    ip: [str(h).lower() for h in hosts]
                    for ip, hosts in by_ip.items()
                }
                globs = body.get("globals")
                if isinstance(globs, list) and globs:
                    self._bulk_cdn = tuple(str(g).lower() for g in globs)
                blocked = body.get("blocked_ips")
                if isinstance(blocked, list):
                    self._blocked_ips = frozenset(str(ip) for ip in blocked)
            except Exception as e:
                self._log.debug("passthrough refresh failed: %s", e)
            await asyncio.sleep(PASSTHROUGH_REFRESH_SECS)

    def _is_bulk_cdn(self, host: str) -> bool:
        h = (host or "").lower()
        return any(fnmatch.fnmatchcase(h, p) for p in self._bulk_cdn)

    def _passthrough_match(self, client_ip: str, sni: str) -> str | None:
        """Return the matched glob if `sni` should be passed through for
        `client_ip`, else None."""
        sni = (sni or "").lower()
        if not sni:
            return None
        for pat in self._passthrough.get(client_ip, ()):
            if fnmatch.fnmatchcase(sni, pat):
                return pat
        return None

    def _should_emit_tls(self, client_ip: str, host: str, decision: str) -> bool:
        """Coalesce repeated TLS events. Pinned-cert apps retry constantly;
        we only need one event per minute to know it's happening."""
        key = (client_ip, host.lower(), decision)
        now = time.monotonic()
        last = self._tls_event_seen.get(key)
        if last is not None and (now - last) < TLS_EVENT_DEDUP_SECS:
            return False
        self._tls_event_seen[key] = now
        # Cheap bounded eviction — drop entries older than 5 min on every
        # new emit so the dict can't grow unbounded across long sessions.
        cutoff = now - 300
        if len(self._tls_event_seen) > 256:
            self._tls_event_seen = {
                k: v for k, v in self._tls_event_seen.items() if v > cutoff
            }
        return True

    async def _decision(self, client_ip: str, host: str, path: str, query: str | None) -> dict:
        try:
            r = await self._client.post(
                f"{RULES_SVC_URL}/api/decision",
                json={
                    "client_ip": client_ip,
                    "host": host,
                    "path": path,
                    "query": query or "",
                },
            )
            r.raise_for_status()
            return r.json()
        except Exception as e:
            self._log.warning("decision lookup failed: %s", e)
            # Fail open — don't lock the kid out if rules-svc is down.
            return {"action": "allow", "kid": None, "rule": None, "flag": False}

    def _post_event(self, payload: dict) -> None:
        # Fire-and-forget; never block the user's request on this.
        asyncio.create_task(self._send_event(payload))

    async def _send_event(self, payload: dict) -> None:
        try:
            await self._client.post(f"{RULES_SVC_URL}/api/events", json=payload)
        except Exception as e:
            self._log.debug("event post failed: %s", e)

    def _post_tls_failure(self, client_ip: str, host: str) -> None:
        # Fire-and-forget; never block TLS handshake handling on this.
        asyncio.create_task(self._send_tls_failure(client_ip, host))

    async def _send_tls_failure(self, client_ip: str, host: str) -> None:
        try:
            await self._client.post(
                f"{RULES_SVC_URL}/api/tls-failures",
                json={"client_ip": client_ip, "host": host},
            )
        except Exception as e:
            self._log.debug("tls-failure post failed: %s", e)

    async def request(self, flow: http.HTTPFlow) -> None:
        req = flow.request
        client_ip = flow.client_conn.peername[0] if flow.client_conn.peername else ""
        host = req.pretty_host
        path = req.path.split("?", 1)[0] if "?" in req.path else req.path
        # Always pass a string-or-None — earlier we relied on `req.query.fields`
        # truthiness, but empty-fields returns an empty *list* which (after JSON
        # round-trip) violated the DB's TEXT column and crashed the event insert.
        query = req.url.split("?", 1)[1] if "?" in req.url else None

        decision = await self._decision(client_ip, host, path, query)
        action = decision.get("action", "allow")
        rule = decision.get("rule")
        kid = decision.get("kid")
        flag = bool(decision.get("flag"))

        if action == "block":
            flow.response = http.Response.make(
                403, BLOCK_PAGE, {"Content-Type": "text/html; charset=utf-8"},
            )

        # Send every event to rules-svc; the server-side handler now decides
        # what hits the raw `events` table (page/iframe navigations + any
        # block/flag/tls_failed/dns_block) versus what just bumps the
        # `domain_stats` counters. Bulk-CDN traffic still gates the raw
        # insert via the kind classifier (asset/xhr) but contributes to
        # per-domain counters so the overview reflects real volume.
        self._post_event(
            {
                "client_ip": client_ip,
                "method": req.method,
                "host": host,
                "path": path,
                "query": query,
                "decision": action if action in {"allow", "block", "flag"} else "allow",
                "rule": rule,
                "flag": flag,
                "sni_only": False,
                "status": 403 if action == "block" else None,
                "kind": _classify(req),
            }
        )

    async def response(self, flow: http.HTTPFlow) -> None:
        # We log at request time; nothing extra to do here for now.
        pass

    def tls_clienthello(self, data: ClientHelloData) -> None:
        """Inspect the SNI before the TLS handshake completes. If the kid's
        passthrough list matches, tunnel TLS untouched so pinned-cert apps
        can speak directly to the origin and survive."""
        try:
            sni = data.client_hello.sni or ""
            client_ip = (
                data.context.client.peername[0]
                if data.context.client.peername
                else ""
            )
        except Exception:
            return
        if not sni or not client_ip:
            return
        # If the client is currently network-blocked (schedule out-of-window /
        # manual block / kid-wide block), refuse to passthrough — let the
        # connection fall through to normal MITM so /api/decision serves the
        # block page. Otherwise schedule enforcement leaks: nft's :443 reject
        # exempts mitm clients on purpose, trusting us to enforce policy here.
        if client_ip in self._blocked_ips:
            return
        # Bulk-content CDNs (Steam, Windows Update, etc.) are passed through
        # globally — no per-kid opt-in. Decrypting GBs of game binaries is
        # pure CPU cost with no parental-control benefit.
        if self._is_bulk_cdn(sni):
            data.ignore_connection = True
            return
        matched = self._passthrough_match(client_ip, sni)
        if not matched:
            return
        data.ignore_connection = True
        # Counter-only emit: we can't see inside the encrypted stream, but
        # we know this kid is hitting this SNI. The server-side gating drops
        # this row from the raw `events` table (decision=passthrough not in
        # the persist set, kind=None) — the only effect is bumping
        # `domain_stats` so passthrough domains still appear in the
        # overview's top-hosts panel. Without this, sites the parent
        # whitelisted (reddit, guardian, youtube, ...) are invisible to the
        # dashboard, which is the opposite of useful.
        self._post_event(
            {
                "client_ip": client_ip,
                "method": None,
                "host": sni,
                "path": None,
                "query": None,
                "decision": "passthrough",
                "rule": matched,
                "flag": False,
                "sni_only": False,
                "status": None,
                "kind": None,
            }
        )

    def tls_failed_client(self, data: TlsData) -> None:
        """The client refused our cert — record the SNI so the Passthrough
        tab can offer it as a candidate.

        We upsert into the tls_failures table (one row per (kid, host)) and
        deliberately do NOT touch the activity log: pinned-cert apps retry
        constantly and would dominate the feed otherwise. The per-minute
        dedup window further caps the upsert traffic, since the same
        ClientHello stream produces dozens of failed handshakes per minute.
        """
        try:
            host = data.context.client.sni or ""
            client_ip = data.context.client.peername[0] if data.context.client.peername else ""
        except Exception:
            return
        if not host or _is_sni_noise(host):
            return
        if not self._should_emit_tls(client_ip, host, "tls_failed"):
            return
        self._post_tls_failure(client_ip, host)


addons = [GdlfAddon()]
