/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KidsIndexRouteImport } from './routes/kids.index'
import { Route as KidsNameIndexRouteImport } from './routes/kids.$name.index'
import { Route as KidsNameRulesNewRouteImport } from './routes/kids.$name.rules.new'
import { Route as KidsNameDevicesNewRouteImport } from './routes/kids.$name.devices.new'
import { Route as KidsNameRulesIdxEditRouteImport } from './routes/kids.$name.rules.$idx.edit'
import { Route as KidsNameDevicesIpEnrolRouteImport } from './routes/kids.$name.devices.$ip.enrol'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIndexRoute = KidsIndexRouteImport.update({
  id: '/kids/',
  path: '/kids/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsNameIndexRoute = KidsNameIndexRouteImport.update({
  id: '/kids/$name/',
  path: '/kids/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsNameRulesNewRoute = KidsNameRulesNewRouteImport.update({
  id: '/kids/$name/rules/new',
  path: '/kids/$name/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsNameDevicesNewRoute = KidsNameDevicesNewRouteImport.update({
  id: '/kids/$name/devices/new',
  path: '/kids/$name/devices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsNameRulesIdxEditRoute = KidsNameRulesIdxEditRouteImport.update({
  id: '/kids/$name/rules/$idx/edit',
  path: '/kids/$name/rules/$idx/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsNameDevicesIpEnrolRoute = KidsNameDevicesIpEnrolRouteImport.update({
  id: '/kids/$name/devices/$ip/enrol',
  path: '/kids/$name/devices/$ip/enrol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/kids/': typeof KidsIndexRoute
  '/kids/$name/': typeof KidsNameIndexRoute
  '/kids/$name/devices/new': typeof KidsNameDevicesNewRoute
  '/kids/$name/rules/new': typeof KidsNameRulesNewRoute
  '/kids/$name/devices/$ip/enrol': typeof KidsNameDevicesIpEnrolRoute
  '/kids/$name/rules/$idx/edit': typeof KidsNameRulesIdxEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/kids': typeof KidsIndexRoute
  '/kids/$name': typeof KidsNameIndexRoute
  '/kids/$name/devices/new': typeof KidsNameDevicesNewRoute
  '/kids/$name/rules/new': typeof KidsNameRulesNewRoute
  '/kids/$name/devices/$ip/enrol': typeof KidsNameDevicesIpEnrolRoute
  '/kids/$name/rules/$idx/edit': typeof KidsNameRulesIdxEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/kids/': typeof KidsIndexRoute
  '/kids/$name/': typeof KidsNameIndexRoute
  '/kids/$name/devices/new': typeof KidsNameDevicesNewRoute
  '/kids/$name/rules/new': typeof KidsNameRulesNewRoute
  '/kids/$name/devices/$ip/enrol': typeof KidsNameDevicesIpEnrolRoute
  '/kids/$name/rules/$idx/edit': typeof KidsNameRulesIdxEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/login'
    | '/settings'
    | '/kids/'
    | '/kids/$name/'
    | '/kids/$name/devices/new'
    | '/kids/$name/rules/new'
    | '/kids/$name/devices/$ip/enrol'
    | '/kids/$name/rules/$idx/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/login'
    | '/settings'
    | '/kids'
    | '/kids/$name'
    | '/kids/$name/devices/new'
    | '/kids/$name/rules/new'
    | '/kids/$name/devices/$ip/enrol'
    | '/kids/$name/rules/$idx/edit'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/login'
    | '/settings'
    | '/kids/'
    | '/kids/$name/'
    | '/kids/$name/devices/new'
    | '/kids/$name/rules/new'
    | '/kids/$name/devices/$ip/enrol'
    | '/kids/$name/rules/$idx/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  KidsIndexRoute: typeof KidsIndexRoute
  KidsNameIndexRoute: typeof KidsNameIndexRoute
  KidsNameDevicesNewRoute: typeof KidsNameDevicesNewRoute
  KidsNameRulesNewRoute: typeof KidsNameRulesNewRoute
  KidsNameDevicesIpEnrolRoute: typeof KidsNameDevicesIpEnrolRoute
  KidsNameRulesIdxEditRoute: typeof KidsNameRulesIdxEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/': {
      id: '/kids/'
      path: '/kids'
      fullPath: '/kids/'
      preLoaderRoute: typeof KidsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$name/': {
      id: '/kids/$name/'
      path: '/kids/$name'
      fullPath: '/kids/$name/'
      preLoaderRoute: typeof KidsNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$name/rules/new': {
      id: '/kids/$name/rules/new'
      path: '/kids/$name/rules/new'
      fullPath: '/kids/$name/rules/new'
      preLoaderRoute: typeof KidsNameRulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$name/devices/new': {
      id: '/kids/$name/devices/new'
      path: '/kids/$name/devices/new'
      fullPath: '/kids/$name/devices/new'
      preLoaderRoute: typeof KidsNameDevicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$name/rules/$idx/edit': {
      id: '/kids/$name/rules/$idx/edit'
      path: '/kids/$name/rules/$idx/edit'
      fullPath: '/kids/$name/rules/$idx/edit'
      preLoaderRoute: typeof KidsNameRulesIdxEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$name/devices/$ip/enrol': {
      id: '/kids/$name/devices/$ip/enrol'
      path: '/kids/$name/devices/$ip/enrol'
      fullPath: '/kids/$name/devices/$ip/enrol'
      preLoaderRoute: typeof KidsNameDevicesIpEnrolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  KidsIndexRoute: KidsIndexRoute,
  KidsNameIndexRoute: KidsNameIndexRoute,
  KidsNameDevicesNewRoute: KidsNameDevicesNewRoute,
  KidsNameRulesNewRoute: KidsNameRulesNewRoute,
  KidsNameDevicesIpEnrolRoute: KidsNameDevicesIpEnrolRoute,
  KidsNameRulesIdxEditRoute: KidsNameRulesIdxEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
